### PR TITLE
Questions

### PR DESCRIPTION
**Pull request by Anasshahidd21**
polling

Updated the polling, now it can add/remove the poll options dynamically.

### CODE REVIEW

**Comment by ghaithdallaali** [comment]
Does this conform with the latest UX spec?

**Comment by Anasshahidd21** [comment]
> Does this conform with the latest UX spec?

No it doesn't. I'll update it soon enough. Should the polls be kept dynamic or static, the way it is set up in the design is it only allows 4 options, is that how we want to keep it? or should we keep it dynamic like I did. @ghaithdallaali

**Review by ghaithdallaali — APPROVED** [review]
Keep it dynamic please. Merge this as-is for now, and we can update the CSS after (it might change again).
Let's keep our PRs small.

**Comment by ghaithdallaali** [comment]
@Anasshahidd21 are you still working on this or can we merge it?

**Pull request merged**
